[package]
name = "gearley"
version = "0.0.2"

authors = [ "Piotr Czarnecki <pioczarn@gmail.com>" ]
description = "An Earley parser engine."
keywords = ["grammar", "parsing", "language", "forest", "intersection"]
documentation = "http://pczarn.github.io/gearley/"
repository = "https://github.com/pczarn/gearley"
license = "MIT/Apache-2.0"

[profile.release]
debug = true

[lib]
name = "gearley"

[dependencies]
cfg = "0.4"
bit-matrix = { version = "0.4", features = ["serialize"] }
bit-vec = "0.6"
optional = { version = "0.5", features = ["serde"] }
ref_slice = "1.1"
num = "0.2"
num-traits = "0.2"
num-derive = "0.2"
log = "0.4"
env_logger = "0.5"
serde = "1.0"
serde_derive = "1.0"
