[workspace]

members = [
    "gearley",
    "gearley-recognizer",
    "gearley-grammar",
    "gearley-default-grammar",
    "gearley-forest",
    "compact-bocage",
    "simple-bocage",
]

resolver = "2"
