[package]
name = "gearley"
version = "0.0.1"

authors = [ "Piotr Czarnecki <pioczarn@gmail.com>" ]
description = "An Earley parser engine."
keywords = ["grammar", "parsing", "language", "forest", "intersection"]
documentation = "http://pczarn.github.io/gearley/"
repository = "https://github.com/pczarn/gearley"
license = "MIT/Apache-2.0"

[lib]
name = "gearley"

[dependencies]
cfg = "0.3"
bit-matrix = "0.2"
optional = "0.0"
ref_slice = "1.0"
typed-arena = "1.2"
